### ISSUE TITLE
NixFlakes: `dev-shell` marked for deprecation?

### ISSUE THREAD

**Issue by blaggacao** [zimbatm/wiki#8]
https://github.com/NixOS/nix/blob/3f264916dbfe346a71fa4182c9037332ac54f9d9/src/nix/main.cc#L114

**Comment by blaggacao** [comment]
See also: https://github.com/NixOS/nix/pull/3833 for the countaerpart `devShell`

**Comment by Mic92** [comment]
It's simply called `nix develop` now.
